In [ ]:
import numpy as np
import scipy.linalg as la

In [ ]:
mat1 = np.array([[1,2,3], [4,5,6]])
mat2 = np.asmatrix('[1 2;3 4]')

In [ ]:
#dense matrix
print(mat1, mat2)
import scipy

# sparse matrix
sm = scipy.sparse.csr_matrix(mat2)
print(sm)

[[1 2 3]
 [4 5 6]] [[1 2]
 [3 4]]
  (0, 0)	1
  (0, 1)	2
  (1, 0)	3
  (1, 1)	4


In [ ]:
np.trace(mat1)

6

In [ ]:
np.linalg.det(mat2)

-2.0000000000000004

In [ ]:
np.linalg.inv(mat2)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [ ]:
np.shape(mat1)

(2, 3)

In [ ]:
mat2+mat2

matrix([[2, 4],
        [6, 8]])

In [ ]:
mat2*mat2

matrix([[ 7, 10],
        [15, 22]])

In [ ]:
np.cross(mat2, mat2)

array([0, 0])

In [ ]:
np.linalg.pinv(mat2)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [ ]:
np.linalg.matrix_rank(mat2)

2

In [ ]:
from scipy.linalg import eig
eigval, eigvec = eig(mat2)
print(eigval, eigvec)

[-0.37228132+0.j  5.37228132+0.j] [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
#matrix decompositions
from scipy.linalg import svd, lu, qr

U, S, V = svd(mat2)
P, L, U = lu(mat2)
Q, R = qr(mat2)

In [ ]:
# Norms

frobenius_norm = np.linalg.norm(mat2)
L1_norm = np.linalg.norm(mat2, ord=1)
L2_norm = np.linalg.norm(mat2, ord=2)
infinity_norm = np.linalg.norm(mat2, ord=np.inf)